### PR TITLE
crack

### PR DESCRIPTION
**Pull request by Rundas01**
lol

### CODE REVIEW

**Comment by lynxx131** [comment]
Seems to be a small issue with the PBF, it accepts fuel and ingots in any slot combination rather then the appropriate slots as indicated by the pictures.

https://i.imgur.com/cg1Jatw.png
https://i.imgur.com/8OCmIq8.png

Both of the above worked, it should only work with the iron in the top slot and the coal in the bottom slot.

**Comment by lynxx131** [comment]
Also I don't appear to be able to right click fill the laver boiler with a lava bucket or place a lava bucket in the GUI.

Right click filling the lava boiler's water gauge with a water bucket works fine.

**Comment by Vliro** [comment]
The first issue is simply because it doesn't differentiate slot types so it's as expected for now.

**Comment by Rundas01** [comment]
> Also I don't appear to be able to right click fill the laver boiler with a lava bucket or place a lava bucket in the GUI.
>
Just put a Lava Bucket in (as an item). I dunno how to make it accept liquid Lava tbh.

**Comment by lynxx131** [comment]
The GUI issue with not being able to place the bucket into any slots is only limited to the bronze lava boiler, the steel lava boiler works perfectly fine.

I think its due to `LAVA_BOILER.add(BRONZE, CELL_IN, 44, 26).add(BRONZE, CELL_OUT, 44, 62).add(BRONZE, IT_OUT, 116, 26).add(BRONZE, IT_IN, 116, 62);` not being present in `Guis.java`.

**Pull request closed without merging**
