### PR TITLE
finshed fission fuels

### PR DESCRIPTION
**Pull request by Rundas01**

### CODE REVIEW

**Comment by Vliro** [comment]
great work dude. What's the plan for the actual reactor in the future

**Comment by Rundas01** [comment]
> great work dude. What's the plan for the actual reactor in the future

ayy, you're actually not dead xD
my plans are the following: once there is an idea how to implement a materialitem with 2 associated materials, I'll add breeder fuels. their primary usage is getting isotopes with higher protons in their nucleus (which yields more energy when put in a fissile fuel).

**Comment by Vliro** [comment]
You can just make a new item that extends ItemBasic.

I meant as a reactor , multi block that is

**Comment by Trinsdar** [comment]
About double material items: i've actually been working on something on a separate branch

**Comment by Rundas01** [comment]
> You can just make a new item that extends ItemBasic.
> 
> I meant as a reactor , multi block that is

it either outputs EU directly, or turns cold coolant into hot coolant which can be pumped into a separate turbine

**Comment by Trinsdar** [comment]
I prefer the latter method, makes more sense, as that's how it works irl

**Comment by Rundas01** [comment]
I hate submodules so much 😂

**Pull request closed without merging**
