### PR TITLE
Content me bois

### PR DESCRIPTION
**Pull request by Rundas01**
za hando

### CODE REVIEW

**Comment by Trinsdar** [comment]
would you be able to port these changes over to fabric-1.18? you should be able to pretty much just copy and paste most of them from src to common/src, gti barely changed when it was ported

**Comment by Rundas01** [comment]
> would you be able to port these changes over to fabric-1.18? you should be able to pretty much just copy and paste most of them from src to common/src, gti barely changed when it was ported

I suppose I can do that. But the question is whether I even want to invest my time into developing a mod for a mod loader which I won't even be using. Most of the mods I care about use Forge, so if GT will only be available on Fabric, I'm out.

**Comment by Trinsdar** [comment]
> > would you be able to port these changes over to fabric-1.18? you should be able to pretty much just copy and paste most of them from src to common/src, gti barely changed when it was ported
> 
> I suppose I can do that. But the question is whether I even want to invest my time into developing a mod for a mod loader which I won't even be using. Most of the mods I care about use Forge, so if GT will only be available on Fabric, I'm out.

It's going to be on both

**Comment by Rundas01** [comment]
aight, will continue to give my best in that case :3

**Comment by Trinsdar** [comment]
@Rundas01 can you redo this pr on the dev-1.18 branch?

**Pull request closed without merging**
