### PR TITLE
John Wheatfield's TFC Integration work

### PR DESCRIPTION
**Pull request by rchpweblo**
Added Antimatter tool compatibility to TFC logs for stripping and TFC soil for hoeing and shoveling.
Will require my Antimatter PR for the shovel to function.

### CODE REVIEW

**Review by Trinsdar — APPROVED** [review]

**Comment by rchpweblo** [comment]
BTW the reason this failed is because the version of the Antimatter submodule needs to be updated to the latest version. Currently the linked version does not have the new shovel code.

**Comment by Trinsdar** [comment]
Yah I'm aware

**Comment by Trinsdar** [comment]
@rchpweblo what's the status on this pr? If you're not going to be able to get the other changes you wanted anytime soon I'll just go ahead and merge this and then you can make another pr at a later date

**Comment by rchpweblo** [comment]
Well, I still need to do some work on iron compatibility, but
unfortunately, I've been very busy for the last few months.  However, with
the holidays coming up, things are finally letting up. This has been the
first week that wasn't a total storm in a while so I'll probably have time
to work on it again this weekend.

**Comment by Trinsdar** [comment]
I've decided to merge this anyways, since I'm moving all work on gti over to https://github.com/GT-Reimagined/GT5-Reimagined. Please make the rest of the changes in a new pr over there

**Comment by rchpweblo** [comment]
understood
I'll have to take a look to see what I had that wasn't pushed yet, I know there were quite a few things that were only locally pushed as I hadn't finished them yet

**Pull request merged**
