### PR TITLE
added machine classes stub

### PR DESCRIPTION
**Pull request by koiNoCirculation**
Adding single machine classes, which are some todo classes.
They are from gt5u/gt new horizons @ 1.7.10.

### CODE REVIEW

**Comment by Rongmario** [comment]
There's no need for these classes! These machines (which are basic/simple) are defined in muramasa.gti.data.Machines!

BasicMachine also allows a TileEntityMachine supplier if we do implement custom logic for some machines.

**Comment by koiNoCirculation** [comment]
@Rongmario Yes, I know the core of machines are Collection[Itemstack] => Another Collection[Itemstack] with energy, that's pretty good, Machine class has done that.
But I don't think there's no need of Separate TileEntityMachine classes.Because there's many unique things there, like slots linking to gui or cleanroom magic, though some machines shares almost the same gui. So there's need of calling ctor of BasicMachine with Tile supplier on every machine. So why not using seperated classes? You mean lambda or anomynous classes? That' ugly I think.

**Comment by Rongmario** [comment]
There's no cleanroom stuff implemented nor suggested or even in the pipelines yet, if that was the case, there would be a more elegant solution than to implement individual classes.

I believe slots will be changed to integrate with RecipeMaps, to ensure an easier check of capping RecipeMaps inputs/outputs to not exceed slot count of said machine, I'll have to get back to you on that. Right now they're defined in muramasa.gti.data.Guis.

I also believe that it is a lot more uglier having an abundance of classes that will probably be of couple lines long defining literally nothing but ids and extending off a base tile. When a class is deemed necessary for a more complex machine, supplier should take care of that cleanly.

**Comment by koiNoCirculation** [comment]
@Rongmario 
OK, you are using a common way to register gui.
But look:
        HATCH_ITEM_O.getGui().add(HV, IT_OUT, 52, 7).add(HV, IT_OUT, 70, 7).add(HV, IT_OUT, 88, 7).add(HV, IT_OUT, 106, 7).add(HV, IT_OUT, 52, 25).add(HV, IT_OUT, 70, 25).add(HV, IT_OUT, 88, 25).add(HV, IT_OUT, 106, 25).add(HV, IT_OUT, 52, 43).add(HV, IT_OUT, 70, 43).add(HV, IT_OUT, 88, 43).add(HV, IT_OUT, 106, 43).add(HV, IT_OUT, 52, 61).add(HV, IT_OUT, 70, 61).add(HV, IT_OUT, 88, 61).add(HV, IT_OUT, 106, 61);
Too long code in a line(chain calls).
That must be a 4X4 inventory of a output bus, looks shitty.

Using config like xml or json could be a better way, especially when working on recipes.
There are too many recipes, we can dump recipes from gt5u instead of reworking on ourselves with xml format and load on 1.15.

**Comment by Rongmario** [comment]
I really don't know what you're coming in at, your latter paragraph has nothing to do with the gui, please speak on discord if you have any concerns pertaining recipes and jsons.

**Comment by Rongmario** [comment]
As for the comments of chain call, it can be reduced to loop, its just verbose at the moment. Feel free to PR that.

**Pull request closed without merging**
