### PR TITLE
Added translation features for gradle and create Russian lang files

### PR DESCRIPTION
**Pull request by qubka**

### CODE REVIEW

**Comment by Muramasa-** [comment]
It would be a lot cleaner if this could be moved to its own project?

**Comment by CrossVas** [comment]
If the ru_ru file is generated automatically, that's great, but there are some transactions of items that don't respect the case. For instance: Мелкая пыль Редстоун or Мелкая пыль соль

**Comment by qubka** [comment]
Remove all irrelevant, except translation file

**Comment by qubka** [comment]
> If the ru_ru file is generated automatically, that's great, but there are some transactions of items that don't respect the case. For instance: Мелкая пыль Редстоун or Мелкая пыль соль
> 
> EDIT: There could be more instances.

Thanks

**Pull request merged**
