### PR TITLE
added recycler

### PR DESCRIPTION
**Pull request by Rundas01**
+ some other stuff

### CODE REVIEW

**Comment by Rongmario** [comment]
This is some memory hog stuff, I'd rather have custom recipe checking for the Recycler if we're going to add one.

**Comment by Vliro** [comment]
I will add a custom ingredient that overrides test() with its own HashSet of a blacklist(for stuff like cobble etc), just haven't gotten around to it

**Comment by Rongmario** [comment]
Yeah just noting it here since I haven't seen any discussion about it over on discord

**Comment by Rundas01** [comment]
obsolete and needs discussion

**Pull request closed without merging**
